### ISSUE TITLE
Atom feed contains relative href on self link

### ISSUE THREAD

**Issue by Kristine1975** [Marc-B-Reynolds/Marc-B-Reynolds.github.io#1]
Hello Marc,

your blog's Atom feed at http://marc-b-reynolds.github.io/feed.xml contains the tag `<atom:link href="/feed.xml" rel="self" type="application/rss+xml" />` with a relative instead of absolute `href`. Unfortunately this causes problems with some news readers (in my case NetNewsWire) and also seems to violate the Atom spec [according to this W3C validator]( https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fmarc-b-reynolds.github.io%2Ffeed.xml).

I think the fix would be as simple as prefixing the `href` with `http://marc-b-reynolds.github.io/`:

>`<atom:link href="http://marc-b-reynolds.github.io/feed.xml" rel="self" type="application/rss+xml" />`

P.S: Thank you for writing your very interesting blog!

**Comment by Marc-B-Reynolds** [comment]
Thanks for the info (I have no clue what I'm doing WRT web-stuff).  Updated and the validator now seems happy, don't know if the data it contains is correct.

**Comment by Kristine1975** [comment]
Looks good to me. There's a double slash (instead of a single slash) after the domain name like `http://marc-b-reynolds.github.io//distribution/2017/01/27/UniformRot.html`, but that doesn't seem to cause any trouble.

Thank you for fixing this!
